Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.vm.box_version = "1905.1"
  config.vm.synced_folder "/Users/afonsomukai/Projects/code", "/home/vagrant/code"
  config.vm.network "private_network", ip: "192.168.98.123"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "8192"
    vb.cpus = "4"
  end
  config.vm.provision "shell", path: "provision.sh"
end
