Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  # config.vm.synced_folder "<src>", "/home/vagrant/code"
  config.vm.network "private_network", ip: "192.168.98.122"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "8192"
    vb.cpus = 4
  end
  config.vm.provision "shell", path: "provision.sh"
end
